refresher:
  refreshInterval: 60
gui:
  useHunkModeInDiffView: false
  mainPanelSplitMode: "horizontal"
  theme:
    selectedLineBgColor:
      - "#413660"
git:
  autoFetch: true
  diffRenderers:
    - colorArg: always
      type: rawGit
  commit:
    signOff: true
  pull:
    mode: "rebase"
