refresher:
  refreshInterval: 60
gui:
  useHunkModeInStagingView: false
  mainPanelSplitMode: "horizontal"
  theme:
    selectedLineBgColor:
      - "#413660"
git:
  autoFetch: true
  pagers:
    - colorArg: always
  commit:
    signOff: true
  pull:
    mode: "rebase"
