# use_thin_strokes = true
[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/dracula.toml"]

[keyboard]
bindings = [
  { key = "F", mods = "Control", action = "SearchForward" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Space", mods = "Control", chars = "\u0000" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
]

[font]
size = 22

[font.normal]
family = "Terminess Nerd Font"
style = "Regular"

# [font.bold]
# family = "Teminess Nerd Font"
# style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Terminess Nerd Font"
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

# [mouse.hints]
# modifiers = "Command"

# [mouse.hints.launcher]
# program = "open"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = true

# Unused
[colors.bright]
black = "0x7f7f7f"
blue = "0x5c5cff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[colors.normal]
black = "0x000000"
blue = "0x0000ee"
cyan = "0x00cdcd"
green = "0x00cd00"
magenta = "0xcd00cd"
red = "0xcd0000"
white = "0xe5e5e5"
yellow = "0xcdcd00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[colors.search.focused_match]
background = "#ab4642"
foreground = "#181818"

# [colors.search.footer_bar]
# background = "#262626"
# foreground = "#d0d0d0"

[colors.search.matches]
background = "#f4bf75"
foreground = "#181818"
